import { User, GuardianContact, SafePoint, IncidentReport, EvidenceItem, RouteOption, AIRiskTrend, HotspotZone, CampusSafetyAlert } from '@/types';

export const mockUsers: Record<string, User> = {
  user: {
    id: 'usr_001',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    phone: '+91 98765 43210',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    city: 'Bengaluru',
    campusOrg: 'Christ University Campus',
    emergencyContactsCount: 3,
    consentPoliceDispatch: false, // Privacy default: No automatic police dispatch unless chosen
    consentAudioRecording: true,
    consentLocationTracking: true,
    nightSafetyMode: true,
    collegeSafetyMode: true,
    discreetPin: '1234',
  },
  guardian: {
    id: 'grd_001',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@example.com',
    phone: '+91 98765 11223',
    role: 'guardian',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    city: 'Bengaluru',
    consentPoliceDispatch: false,
    consentAudioRecording: true,
    consentLocationTracking: true,
    nightSafetyMode: false,
    collegeSafetyMode: false,
    discreetPin: '1234',
  },
  authority: {
    id: 'aut_001',
    name: 'Inspector Anita Desai',
    email: 'anita.desai@ksp.gov.in',
    phone: '+91 94808 00001',
    role: 'authority',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    city: 'Bengaluru City Police - Central Command',
    consentPoliceDispatch: true,
    consentAudioRecording: true,
    consentLocationTracking: true,
    nightSafetyMode: false,
    collegeSafetyMode: false,
    discreetPin: '1234',
  },
  organization: {
    id: 'org_001',
    name: 'Campus Safety Cell - Christ University',
    email: 'safety@christuniversity.in',
    phone: '+91 80 4012 9100',
    role: 'organization',
    avatar: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
    city: 'Bengaluru Central',
    campusOrg: 'Christ University',
    consentPoliceDispatch: false,
    consentAudioRecording: true,
    consentLocationTracking: true,
    nightSafetyMode: true,
    collegeSafetyMode: true,
    discreetPin: '1234',
  },
  admin: {
    id: 'adm_001',
    name: 'SafeCircle Global Operations Admin',
    email: 'admin@safecircle.org',
    phone: '+91 800 555 0199',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    city: 'Global Security Ops',
    consentPoliceDispatch: true,
    consentAudioRecording: true,
    consentLocationTracking: true,
    nightSafetyMode: false,
    collegeSafetyMode: false,
    discreetPin: '1234',
  }
};

export const mockGuardianContacts: GuardianContact[] = [
  {
    id: 'g_01',
    name: 'Rajesh Sharma',
    relation: 'Father',
    phone: '+91 98765 11223',
    email: 'rajesh.sharma@example.com',
    priority: 1,
    isLinked: true,
    batteryLevel: 84,
    lastSeen: '2 mins ago',
    liveLocationActive: true,
  },
  {
    id: 'g_02',
    name: 'Dr. Meera Sharma',
    relation: 'Mother',
    phone: '+91 98765 11224',
    email: 'meera.sharma@example.com',
    priority: 1,
    isLinked: true,
    batteryLevel: 92,
    lastSeen: 'Just now',
    liveLocationActive: true,
  },
  {
    id: 'g_03',
    name: 'Ananya Roy',
    relation: 'Roommate / Best Friend',
    phone: '+91 99887 65432',
    email: 'ananya.roy@example.com',
    priority: 2,
    isLinked: true,
    batteryLevel: 67,
    lastSeen: '12 mins ago',
    liveLocationActive: false,
  },
  {
    id: 'g_04',
    name: 'Karan Patel',
    relation: 'Brother',
    phone: '+91 98223 44556',
    email: 'karan.patel@example.com',
    priority: 3,
    isLinked: false,
    batteryLevel: 45,
    lastSeen: '1 hour ago',
    liveLocationActive: false,
  }
];

export const mockSafePoints: SafePoint[] = [
  {
    id: 'sp_01',
    name: 'Apollo 24/7 Pharmacy & First Aid Haven',
    category: 'pharmacy',
    address: '100 Feet Rd, Indiranagar, Bengaluru',
    phone: '+91 80 2525 0001',
    lat: 12.9716,
    lng: 77.6412,
    verified: true,
    distance: '350m',
    openHours: '24 Hours / 7 Days',
    facilities: ['CCTV Monitored', 'Security Guard', 'First Aid Staff', 'Free Emergency Phone', 'Well Lit Waiting Area'],
    contactPerson: 'Pharmacist-in-Charge Manoj',
    rating: 4.9,
  },
  {
    id: 'sp_02',
    name: 'Indiranagar Police Station (Pink Police Outpost)',
    category: 'police',
    address: 'CMH Road, Indiranagar, Bengaluru',
    phone: '112 / 080 2294 2542',
    lat: 12.9784,
    lng: 77.6408,
    verified: true,
    distance: '650m',
    openHours: '24/7 Active Duty',
    facilities: ['Women Helpdesk', 'Pink Police Patrol Vehicle', 'Instant FIR Support', 'Counseling Room'],
    contactPerson: 'Sub-Inspector Roopa',
    rating: 4.8,
  },
  {
    id: 'sp_03',
    name: 'Christ University Central Campus Security Post 1',
    category: 'campus_security',
    address: 'Hosur Road, Bhavani Nagar, Bengaluru',
    phone: '+91 80 4012 9199',
    lat: 12.9345,
    lng: 77.6060,
    verified: true,
    distance: '1.2km',
    openHours: '24/7 Security Desk',
    facilities: ['Safe Walk Escort', 'Hostel Emergency Desk', 'CCTV Network', 'Female Security Personnel'],
    contactPerson: 'Security Officer Samuel',
    rating: 4.9,
  },
  {
    id: 'sp_04',
    name: 'Shell Select Convenience & Fuel Haven 24/7',
    category: 'store_247',
    address: 'Old Airport Road, Kodihalli, Bengaluru',
    phone: '+91 80 4120 7890',
    lat: 12.9602,
    lng: 77.6480,
    verified: true,
    distance: '1.5km',
    openHours: '24/7 Open & Staffed',
    facilities: ['High-Definition CCTV', 'Drinking Water & Restrooms', 'Well-Lit Forecourt', 'Emergency Cab Booking Assistance'],
    contactPerson: 'Store Supervisor Arshad',
    rating: 4.7,
  },
  {
    id: 'sp_05',
    name: 'St. Philomena’s Multi-Specialty Hospital',
    category: 'hospital',
    address: 'Viveka Nagar, Bengaluru',
    phone: '+91 80 4016 4500',
    lat: 12.9520,
    lng: 77.6180,
    verified: true,
    distance: '1.8km',
    openHours: '24/7 Emergency Casualty',
    facilities: ['Trauma Center', 'Female Doctors on Duty', '24/7 Pharmacy', 'Security Guarded'],
    contactPerson: 'Triage Nurse Supervisor',
    rating: 4.8,
  },
  {
    id: 'sp_06',
    name: 'Sthree Shelter & Women Crisis Support Center',
    category: 'shelter',
    address: 'Koramangala 4th Block, Bengaluru',
    phone: '181 / +91 80 2552 4433',
    lat: 12.9360,
    lng: 77.6250,
    verified: true,
    distance: '2.1km',
    openHours: '24/7 Safe Sanctuary',
    facilities: ['Safe Overnight Stay', 'Legal Aid Counselor', 'Psychological Support', 'Confidential Entry'],
    contactPerson: 'Director Savitri Rao',
    rating: 5.0,
  }
];

export const mockIncidentReports: IncidentReport[] = [
  {
    id: 'rep_001',
    complaintId: 'SC-8924K1',
    title: 'Repeated Catcalling & Stalking Near Metro Station Exit B',
    category: 'stalking',
    description: 'Two individuals on a modified motorcycle followed walking commuters along the unlit service road between 9:30 PM and 10:15 PM.',
    timestamp: '2026-09-24T18:30:00Z',
    locationName: 'Indiranagar Metro Station Exit B Service Lane',
    lat: 12.9780,
    lng: 77.6390,
    isAnonymous: true,
    status: 'action_taken',
    severity: 'high',
    evidenceCount: 2,
    officialFeedback: 'Bengaluru City Police Pink Patrol unit deployed. Increased foot patrol scheduled between 8 PM - 11 PM daily.',
    actionTakenNotes: 'Patrol log #BLR-PK-442 logged. Streetlight maintenance request escalated to BBMP.',
    upvotes: 18,
    reporterId: 'usr_001',
    timeOfDay: 'night'
  },
  {
    id: 'rep_002',
    complaintId: 'SC-7712M3',
    title: 'Broken Street Lights and Complete Darkness for 400 Meters',
    category: 'poor_lighting',
    description: 'All four street lamps along 5th Cross have been dark for over a week, forcing women walking back from coaching classes to use phone torches.',
    timestamp: '2026-09-23T20:15:00Z',
    locationName: '5th Cross Road, Koramangala 6th Block',
    lat: 12.9385,
    lng: 77.6210,
    isAnonymous: true,
    status: 'under_review',
    severity: 'medium',
    evidenceCount: 1,
    officialFeedback: 'Civic department notified. Repair team ticket #BBMP-LT-9029 created.',
    upvotes: 24,
    timeOfDay: 'evening'
  },
  {
    id: 'rep_003',
    complaintId: 'SC-6549P8',
    title: 'Aggressive Cab Driver Refused To Take Standard Route',
    category: 'unsafe_transport',
    description: 'Driver intentionally took an unpaved dark alley despite GPS indicating main avenue. Demanded extra cash and made inappropriate remarks.',
    timestamp: '2026-09-22T23:45:00Z',
    locationName: 'Inner Ring Road Flyover underpass',
    lat: 12.9550,
    lng: 77.6350,
    isAnonymous: false,
    status: 'closed',
    severity: 'critical',
    evidenceCount: 3,
    officialFeedback: 'Cab company banned driver profile; police precinct logged incident and warned driver registry.',
    actionTakenNotes: 'Case closed with verified resolution.',
    upvotes: 31,
    timeOfDay: 'late_night'
  },
  {
    id: 'rep_004',
    complaintId: 'SC-5120T4',
    title: 'Verbal Harassment Outside Campus Gate 3',
    category: 'harassment',
    description: 'Group loitering near tea stall passing lewd remarks to students exiting evening lab sessions.',
    timestamp: '2026-09-24T17:10:00Z',
    locationName: 'Christ University Gate 3, Bhavani Nagar',
    lat: 12.9350,
    lng: 77.6070,
    isAnonymous: true,
    status: 'received',
    severity: 'medium',
    evidenceCount: 1,
    officialFeedback: 'Campus Security notified. Security guard post assigned at Gate 3 from 5 PM to 9 PM.',
    upvotes: 14,
    timeOfDay: 'evening'
  },
  {
    id: 'rep_005',
    complaintId: 'SC-4402Z9',
    title: 'Suspicious Vehicle Loitering Near Bus Stop',
    category: 'suspicious_activity',
    description: 'Tinted car parked for 3 consecutive evenings near the bus shelter with occupants filming passersby.',
    timestamp: '2026-09-21T19:30:00Z',
    locationName: 'CMH Road Bus Stop, Indiranagar',
    lat: 12.9790,
    lng: 77.6430,
    isAnonymous: true,
    status: 'action_taken',
    severity: 'high',
    evidenceCount: 2,
    officialFeedback: 'Police beat constable visited spot. Vehicle details captured on CCTV and owner called in for questioning.',
    upvotes: 27,
    timeOfDay: 'evening'
  }
];

export const mockEvidenceItems: EvidenceItem[] = [
  {
    id: 'ev_01',
    title: 'Audio Note: Threatening Remarks from Cab Driver',
    category: 'Audio Recording',
    mediaType: 'audio',
    size: '1.8 MB',
    timestamp: '2026-09-22 23:48:12',
    hash: 'sha256:8f4c2e7189a0398d09b30c12847aef92e',
    location: 'Inner Ring Road (12.9550° N, 77.6350° E)',
    encrypted: true,
    notes: 'Recorded discreetly using SafeCircle Background Audio trigger during cab deviation.'
  },
  {
    id: 'ev_02',
    title: 'Photo: Vehicle Number Plate (KA 03 MZ 9812)',
    category: 'Photograph Proof',
    mediaType: 'photo',
    size: '3.4 MB',
    timestamp: '2026-09-24 18:32:05',
    hash: 'sha256:3a992be711019a28e9cf984a1e9447d2b',
    location: 'Indiranagar Metro Exit B (12.9780° N, 77.6390° E)',
    encrypted: true,
    notes: 'Motorcycle involved in stalking behavior near metro steps.'
  },
  {
    id: 'ev_03',
    title: 'Incident Screenshot: Harassing SMS & Call Log',
    category: 'Digital Evidence',
    mediaType: 'photo',
    size: '890 KB',
    timestamp: '2026-09-23 21:10:44',
    hash: 'sha256:d91c629f12389aa948b8120e980312cb9',
    location: 'Koramangala 5th Block',
    encrypted: true,
    notes: 'Multiple unsolicited calls from unidentified driver number.'
  }
];

export const mockRouteOptions: RouteOption[] = [
  {
    id: 'route_safer',
    name: 'SafeCircle AI Recommended Safer Route',
    type: 'safer',
    durationMinutes: 18,
    distanceKm: 5.4,
    safetyScore: 96,
    lightingScore: 94,
    policeProximityScore: 90,
    crowdScore: 88,
    cautionZonesCount: 0,
    reasons: [
      '100% lit avenue with high pedestrian density',
      'Passes 3 verified 24/7 Safe Points (Apollo Pharmacy & Pink Police Outpost)',
      'Continuous CCTV coverage by Smart City Project',
      'Bypasses dark underpass with 4 past evening reports'
    ],
    warningNote: 'Adds only 3 minutes compared to the unlit route but avoids 2 high-risk zones.',
    color: '#10b981',
    coordinates: [
      [12.9716, 77.6412],
      [12.9740, 77.6415],
      [12.9770, 77.6420],
      [12.9784, 77.6408],
      [12.9810, 77.6390],
      [12.9830, 77.6375]
    ]
  },
  {
    id: 'route_fastest',
    name: 'Fastest Direct Route (Caution Advised)',
    type: 'fastest',
    durationMinutes: 15,
    distanceKm: 4.8,
    safetyScore: 62,
    lightingScore: 48,
    policeProximityScore: 52,
    crowdScore: 35,
    cautionZonesCount: 2,
    reasons: [
      'Shortest travel time via back alleys and service road',
      'Low traffic congestion'
    ],
    warningNote: 'Caution: Route passes through 5th Cross unlit sector with 4 recent evening incident reports.',
    color: '#f59e0b',
    coordinates: [
      [12.9716, 77.6412],
      [12.9725, 77.6380],
      [12.9750, 77.6355],
      [12.9780, 77.6360],
      [12.9830, 77.6375]
    ]
  },
  {
    id: 'route_alternative',
    name: 'Main Commercial Arterial Route',
    type: 'alternative',
    durationMinutes: 20,
    distanceKm: 6.1,
    safetyScore: 91,
    lightingScore: 90,
    policeProximityScore: 85,
    crowdScore: 92,
    cautionZonesCount: 0,
    reasons: [
      'Heavy commercial activity with open stores and cafes',
      'Regular bus connectivity and active street presence'
    ],
    color: '#3b82f6',
    coordinates: [
      [12.9716, 77.6412],
      [12.9700, 77.6450],
      [12.9750, 77.6470],
      [12.9800, 77.6440],
      [12.9830, 77.6375]
    ]
  }
];

export const mockAIRiskTrends: AIRiskTrend[] = [
  { hour: '06:00', riskLevel: 12, incidentCount: 1, lightingQuality: 95, policePatrolPresence: 80 },
  { hour: '09:00', riskLevel: 15, incidentCount: 2, lightingQuality: 98, policePatrolPresence: 85 },
  { hour: '12:00', riskLevel: 18, incidentCount: 3, lightingQuality: 100, policePatrolPresence: 75 },
  { hour: '15:00', riskLevel: 22, incidentCount: 4, lightingQuality: 98, policePatrolPresence: 70 },
  { hour: '18:00', riskLevel: 42, incidentCount: 9, lightingQuality: 85, policePatrolPresence: 88 },
  { hour: '20:00', riskLevel: 68, incidentCount: 16, lightingQuality: 60, policePatrolPresence: 72 },
  { hour: '22:00', riskLevel: 86, incidentCount: 24, lightingQuality: 45, policePatrolPresence: 65 },
  { hour: '00:00', riskLevel: 91, incidentCount: 29, lightingQuality: 35, policePatrolPresence: 55 },
  { hour: '02:00', riskLevel: 82, incidentCount: 19, lightingQuality: 30, policePatrolPresence: 50 },
  { hour: '04:00', riskLevel: 55, incidentCount: 8, lightingQuality: 40, policePatrolPresence: 60 }
];

export const mockHotspotZones: HotspotZone[] = [
  {
    id: 'hz_01',
    name: 'Indiranagar Metro Exit B Service Alley',
    lat: 12.9780,
    lng: 77.6390,
    radiusMeters: 250,
    riskLevel: 'high',
    incidentCount: 14,
    dominantCategory: 'stalking',
    peakRiskHours: '09:30 PM - 01:00 AM',
    safetyAdvisory: 'Use main metro concourse exit A. Avoid lonely service lane after 9 PM.'
  },
  {
    id: 'hz_02',
    name: '5th Cross Unlit Stretch (Koramangala)',
    lat: 12.9385,
    lng: 77.6210,
    radiusMeters: 300,
    riskLevel: 'caution',
    incidentCount: 8,
    dominantCategory: 'poor_lighting',
    peakRiskHours: '08:00 PM - 11:30 PM',
    safetyAdvisory: 'Streetlights under municipal repair. Use 80 Feet Main Road instead.'
  },
  {
    id: 'hz_03',
    name: 'Inner Ring Road Underpass',
    lat: 12.9550,
    lng: 77.6350,
    radiusMeters: 200,
    riskLevel: 'high',
    incidentCount: 11,
    dominantCategory: 'unsafe_transport',
    peakRiskHours: '10:00 PM - 03:00 AM',
    safetyAdvisory: 'Ensure cab driver stays on flyover bridge instead of secluded underpass.'
  },
  {
    id: 'hz_04',
    name: 'Christ University Backgate Lane',
    lat: 12.9335,
    lng: 77.6040,
    radiusMeters: 180,
    riskLevel: 'caution',
    incidentCount: 6,
    dominantCategory: 'harassment',
    peakRiskHours: '05:30 PM - 08:30 PM',
    safetyAdvisory: 'Request Safe Walk escort from campus security post #1.'
  }
];

export const mockCampusAlerts: CampusSafetyAlert[] = [
  {
    id: 'ca_01',
    title: 'Late Night Safe Walk Escort Available',
    type: 'safe_walk',
    campusName: 'Christ University Central Campus',
    timestamp: 'Today, 6:00 PM',
    message: 'Students studying at the central library post 8:00 PM can request a campus security escort to the metro station or hostel gate via SafeCircle.',
    active: true
  },
  {
    id: 'ca_02',
    title: 'Increased Pink Patrol on Hosur Main Road',
    type: 'patrol_update',
    campusName: 'City South Zone',
    timestamp: 'Today, 4:30 PM',
    message: 'Bengaluru City Police has deployed 2 Pink Patrol electric vehicles stationed right outside the college main gate.',
    active: true
  }
];
